### ISSUE TITLE
N8: Frontend/Integration Testing

### ISSUE THREAD

**Issue by DanielLimWeiEn** [CS3219-AY2324S1/ay2324s1-course-assessment-g57#30]
Below describes what is to be done for the frontend testing:

## Authentication

- [x] Login Flow
- [x] Login Error Handling
- [x] Register Error Handling
- [x] Register Password Complexity Handling
- [x] Forget Password Handling

## Collaboration

- [x] Collaboration Flow
- [ ] Question Display and (fetch?)
- [x] Video Player
- [x] Code Editor

## Miscellaneous

- [ ] Landing Page questions Display and (crud?)
- [x] Visit the landing page
- [ ] Profile Page Display and (crud?)
