### ISSUE TITLE
Frontend Cleanup

### ISSUE THREAD

**Issue by mslevis** [CS3219-AY2324S1/ay2324s1-course-assessment-g57#35]
- [x] Align elements in a clean and organized layout. 
- [x] Enough spacing between components and page borders. e.g. left border of collab space should not be flushed to the left
- [x] Question Table should be responsive to content in the table and whole table should be within view
- [x] Maintain consistency in spacing throughout the app with consistent margin and padding values for elements that share the same purpose or context
- [x] Get rid of that green in match controls please😭

**Comment by shuimeihe** [comment]
Pages updated

- [ ] Landing page
- [ ] Dashboard
- [ ] Profile page
- [ ] Code editor page
